name: CI

on:
  push:
    branches: [ "main", "feat/*", "fix/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-checks:
    name: Backend Lint and Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.14

      - name: Install dependencies
        run: uv sync

      - name: Run Ruff Linter
        run: uv run ruff check .

      - name: Run Ruff Format Check
        run: uv run ruff format --check .

      - name: Run Pytest
        run: uv run pytest
